FROM nocobase/nocobase:latest

# Expose default NocoBase runtime interface port
EXPOSE 13000

ENV APP_KEY=ChangeThisSuperSecretKeyInProductionEnvironment
ENV DB_DIALECT=postgres
ENV PORT=13000

CMD ["yarn", "start"]
